<?php get_header(); ?>
<?php get_template_part('template-parts/hero'); ?>
<?php get_template_part('template-parts/categories-grid'); ?>
<?php get_template_part('template-parts/delivery-info'); ?>
<?php get_template_part('template-parts/menu-section'); ?>
<?php get_template_part('template-parts/restaurant-info'); ?>
<?php get_template_part('template-parts/catering'); ?>
<?php get_template_part('template-parts/about'); ?>
<?php get_template_part('template-parts/gallery'); ?>
<?php get_template_part('template-parts/reservation'); ?>
<?php get_footer(); ?>
