// Mock data matching real sys_tickets structure from legacy app
export const MOCK_TICKETS = [
  {
    id: 1,
    tid: 'TKT-001',
    code: 'TKT-001',
    subject: 'Payment issue with invoice #1042',
    status: 'Open',
    urgency: 'High',
    priority: 'High',
    department: { id: 1, name: 'Billing' },
    client: { id: 1, name: 'John Smith', email: 'john@example.com' },
    assigned_to: { id: 1, name: 'Manager' },
    email: 'john@example.com',
    cc: '', bcc: '', phone: '', note: '',
    created_at: '2026-05-10T10:00:00Z',
    updated_at: '2026-05-12T14:00:00Z',
    replies_count: 2,
  },
  {
    id: 2,
    tid: 'TKT-002',
    code: 'TKT-002',
    subject: 'Cannot access my account',
    status: 'On Hold',
    urgency: 'Medium',
    priority: 'Medium',
    department: { id: 2, name: 'Technical' },
    client: { id: 2, name: 'Anna Lee', email: 'anna@example.com' },
    assigned_to: null,
    email: 'anna@example.com',
    cc: '', bcc: '', phone: '', note: '',
    created_at: '2026-05-11T09:00:00Z',
    updated_at: '2026-05-13T11:00:00Z',
    replies_count: 1,
  },
  {
    id: 3,
    tid: 'TKT-003',
    code: 'TKT-003',
    subject: 'Request for contract renewal',
    status: 'Closed',
    urgency: 'Low',
    priority: 'Low',
    department: { id: 3, name: 'Sales' },
    client: { id: 3, name: 'Mark Johnson', email: 'mark@example.com' },
    assigned_to: { id: 2, name: 'Support Agent' },
    email: 'mark@example.com',
    cc: '', bcc: '', phone: '', note: '',
    created_at: '2026-05-08T15:00:00Z',
    updated_at: '2026-05-09T16:00:00Z',
    replies_count: 5,
  },
]

export const MOCK_REPLIES = [
  {
    id: 1,
    ticket_id: 1,
    body: 'We are looking into your payment issue and will get back to you shortly.',
    reply_type: 'public',
    author_info: { name: 'Manager', type: 'admin' },
    created_at: '2026-05-11T10:00:00Z',
  },
  {
    id: 2,
    ticket_id: 1,
    body: 'Thank you. Could you please provide the invoice number?',
    reply_type: 'public',
    author_info: { name: 'John Smith', type: 'client' },
    created_at: '2026-05-11T11:00:00Z',
  },
]

export const MOCK_INPUT_DATA = {
  statuses: ['Open', 'On Hold', 'Escalated', 'Closed'],
  priorities: ['Low', 'Medium', 'High', 'Critical'],
  departments: [
    { id: 1, name: 'Billing' },
    { id: 2, name: 'Technical' },
    { id: 3, name: 'Sales' },
  ],
  staff: [
    { id: 1, name: 'Manager' },
    { id: 2, name: 'Support Agent' },
  ],
  customers: [
    { id: 1, name: 'John Smith' },
    { id: 2, name: 'Anna Lee' },
    { id: 3, name: 'Mark Johnson' },
  ],
}
