<?php


namespace App\Services\Zoom;


class Timezone
{

    public function searchTimezone($timezone, $time_utc)
    {
        $time = $name = null;
        $list = $this->getListTimezone();
        foreach($list as $t => $tList){
            foreach($tList as $nameTimezone){
                if($nameTimezone == $timezone) {
                    $name = $timezone;
                }
            }
            if($t == $time_utc) {
                $time = $tList[array_rand($tList)];
            }
        }

        return $name ?? $time ?? $list['+00:00'][0];
    }


    public function getListTimezone()
    {
        /*return [
            "Pacific/Midway",
            "Pacific/Pago_Pago",
            "Pacific/Honolulu",
            "America/Anchorage",
            "America/Vancouver",
            "America/Los_Angeles",
            "America/Tijuana",
            "America/Edmonton",
            "America/Denver",
            "America/Phoenix",
            "America/Mazatlan",
            "America/Winnipeg",
            "America/Regina",
            "America/Chicago",
            "America/Mexico_City",
            "America/Guatemala",
            "America/El_Salvador",
            "America/Managua",
            "America/Costa_Rica",
            "America/Montreal",
            "America/New_York",
            "America/Indianapolis",
            "America/Panama",
            "America/Bogota",
            "America/Lima",
            "America/Halifax",
            "America/Puerto_Rico",
            "America/Caracas",
            "America/Santiago",
            "America/St_Johns",
            "America/Montevideo",
            "America/Araguaina",
            "America/Argentina/Buenos_Aires",
            "America/Godthab",
            "America/Sao_Paulo",
            "Atlantic/Azores",
            "Canada/Atlantic",
            "Atlantic/Cape_Verde",
            "UTC",
            "Etc/Greenwich",
            "Europe/Belgrade",
            "CET",
            "Atlantic/Reykjavik",
            "Europe/Dublin",
            "Europe/London",
            "Europe/Lisbon",
            "Africa/Casablanca",
            "Africa/Nouakchott",
            "Europe/Oslo",
            "Europe/Copenhagen",
            "Europe/Brussels",
            "Europe/Berlin",
            "Europe/Helsinki",
            "Europe/Amsterdam",
            "Europe/Rome",
            "Europe/Stockholm",
            "Europe/Vienna",
            "Europe/Luxembourg",
            "Europe/Paris",
            "Europe/Zurich",
            "Europe/Madrid",
            "Africa/Bangui",
            "Africa/Algiers",
            "Africa/Tunis",
            "Africa/Harare",
            "Africa/Nairobi",
            "Europe/Warsaw",
            "Europe/Prague",
            "Europe/Budapest",
            "Europe/Sofia",
            "Europe/Istanbul",
            "Europe/Athens",
            "Europe/Bucharest",
            "Asia/Nicosia",
            "Asia/Beirut",
            "Asia/Damascus",
            "Asia/Jerusalem",
            "Asia/Amman",
            "Africa/Tripoli",
            "Africa/Cairo",
            "Africa/Johannesburg",
            "Europe/Moscow",
            "Asia/Baghdad",
            "Asia/Kuwait",
            "Asia/Riyadh",
            "Asia/Bahrain",
            "Asia/Qatar",
            "Asia/Aden",
            "Asia/Tehran",
            "Africa/Khartoum",
            "Africa/Djibouti",
            "Africa/Mogadishu",
            "Asia/Dubai",
            "Asia/Muscat",
            "Asia/Baku",
            "Asia/Kabul",
            "Asia/Yekaterinburg",
            "Asia/Tashkent",
            "Asia/Calcutta",
            "Asia/Kathmandu",
            "Asia/Novosibirsk",
            "Asia/Almaty",
            "Asia/Dacca",
            "Asia/Krasnoyarsk",
            "Asia/Dhaka",
            "Asia/Bangkok",
            "Asia/Saigon",
            "Asia/Jakarta",
            "Asia/Irkutsk",
            "Asia/Shanghai",
            "Asia/Hong_Kong",
            "Asia/Taipei",
            "Asia/Kuala_Lumpur",
            "Asia/Singapore",
            "Australia/Perth",
            "Asia/Yakutsk",
            "Asia/Seoul",
            "Asia/Tokyo",
            "Australia/Darwin",
            "Australia/Adelaide",
            "Asia/Vladivostok",
            "Pacific/Port_Moresby",
            "Australia/Brisbane",
            "Australia/Sydney",
            "Australia/Hobart",
            "Asia/Magadan",
            "SST",
            "Pacific/Noumea",
            "Asia/Kamchatka",
            "Pacific/Fiji",
            "Pacific/Auckland",
            "Asia/Kolkata",
            "Europe/Kiev",
            "America/Tegucigalpa",
            "Pacific/Apia"
        ];*/

        return [
            "-11:00" => [
                "Pacific/Pago_Pago",
                "Pacific/Midway",
            ],
            "-10:00" => [
                "Pacific/Honolulu",
            ],
            "-08:00" => [
                "America/Tijuana",
                "America/Anchorage",
            ],
            "-07:00" => [
                "America/Mazatlan",
                "America/Vancouver",
                "America/Los_Angeles",
                "America/Phoenix",
            ],
            "-06:00" => [
                "America/Mexico_City",
                "America/Edmonton",
                "America/Denver",
                "America/Regina",
                "America/Guatemala",
                "America/El_Salvador",
                "America/Managua",
                "America/Costa_Rica",
                "America/Tegucigalpa",
            ],
            "-05:00" => [
                "America/Bogota",
                "America/Lima",
                "America/Winnipeg",
                "America/Chicago",
                "America/Montreal",
                "America/Panama",
            ],
            "-04:30" => [
                "America/Caracas",
            ],
            "-04:00" => [
                "America/Santiago",
                "Canada/Atlantic",
                "America/New_York",
                "America/Indianapolis",
                "America/Puerto_Rico",
            ],
            "-03:00" => [
                "America/Halifax",
                "America/Montevideo",
                "America/Araguaina",
                "America/Argentina/Buenos_Aires",
                "America/Sao_Paulo",
            ],
            "-02:30" => [
                "America/St_Johns",
            ],
            "-01:00" => [
                "Atlantic/Azores",
                "Atlantic/Cape_Verde",
                "America/Godthab",
            ],
            "+00:00" => [
                "UTC",
                "Etc/Greenwich",
                "Atlantic/Reykjavik",
                "Africa/Nouakchott",
                "Europe/Dublin",
                "Europe/London",
                "Europe/Lisbon",
                "Africa/Casablanca",
            ],
            "+01:00" => [
                "CET",
                "Europe/Belgrade",
                "Europe/Copenhagen",
                "Europe/Brussels",
                "Europe/Berlin",
                "Europe/Amsterdam",
                "Europe/Rome",
                "Europe/Stockholm",
                "Europe/Vienna",
                "Europe/Paris",
                "Europe/Madrid",
                "Europe/Warsaw",
                "Europe/Prague",
                "Europe/Budapest",
                "Africa/Bangui",
                "Africa/Algiers",
                "Africa/Tunis",
            ],
            "+02:00" => [
                "Europe/Helsinki",
                "Africa/Harare",
                "Europe/Sofia",
                "Europe/Istanbul",
                "Europe/Athens",
                "Europe/Bucharest",
                "Asia/Jerusalem",
                "Africa/Cairo",
                "Europe/Kiev",
                "Europe/Oslo",
                "Europe/Luxembourg",
                "Europe/Zurich",
                "Africa/Tripoli",
                "Africa/Johannesburg",
                "Africa/Khartoum",
            ],
            "+03:00" => [
                "Africa/Nairobi",
                "Europe/Moscow",
                "Asia/Baghdad",
                "Asia/Kuwait",
                "Asia/Riyadh",
                "Asia/Nicosia",
                "Asia/Beirut",
                "Asia/Damascus",
                "Asia/Amman",
                "Asia/Bahrain",
                "Asia/Qatar",
                "Asia/Aden",
                "Africa/Djibouti",
                "Africa/Mogadishu",
            ],
            "+03:30" => [
                "Asia/Tehran",
            ],
            "+04:00" => [
                "Asia/Muscat",
                "Asia/Baku",
                "Asia/Dubai",
            ],
            "+04:30" => [
                "Asia/Kabul",
            ],
            "+05:00" => [
                "Asia/Tashkent",
            ],
            "+05:30" => [
                "Asia/Calcutta",
                "Asia/Kolkata",
            ],
            "+05:45" => [
                "Asia/Kathmandu",
            ],
            "+06:00" => [
                "Asia/Yekaterinburg",
                "Asia/Almaty",
                "Asia/Dhaka",
                "Asia/Dacca",
            ],
            "+07:00" => [
                "Asia/Novosibirsk",
                "Asia/Bangkok",
                "Asia/Jakarta",
                "Asia/Saigon",
            ],
            "+08:00" => [
                "Asia/Krasnoyarsk",
                "Asia/Hong_Kong",
                "Asia/Taipei",
                "Asia/Kuala_Lumpur",
                "Asia/Singapore",
                "Australia/Perth",
                "Asia/Shanghai",
                "SST",
            ],
            "+09:00" => [
                "Asia/Irkutsk",
                "Asia/Seoul",
                "Asia/Tokyo",
            ],
            "+09:30" => [
                "Australia/Darwin",
                "Australia/Adelaide",
            ],
            "+10:00" => [
                "Asia/Yakutsk",
                "Pacific/Port_Moresby",
                "Australia/Brisbane",
                "Australia/Sydney",
                "Australia/Hobart",
            ],
            "+11:00" => [
                "Asia/Vladivostok",
                "Pacific/Noumea",
            ],
            "+12:00" => [
                "Asia/Magadan",
                "Pacific/Fiji",
                "Pacific/Auckland",
                "Asia/Kamchatka",
            ],
            "+13:00" => [
                "Pacific/Apia",
            ],
        ];
    }
}
