export const Routes = {
  root: '/',
  admin: 'admin',
  dashboard: 'dashboard',
  catalog: 'catalog',
  myOrders: 'myorders',
  transactions: 'transactions',
  documents: 'documents',
  invoices: 'invoices',
  offers: 'offers',
  projects: 'projects',
  knowledgeBase: 'knowledgebase',
  tickets: 'tickets',
  profile: 'profile',
  auth: 'auth',
  signIn: 'signin',
  loginResident: 'loginresident',
  register: 'register',
  resetPassword: 'resetpassword',
  notFound: 'notFound',
}

export const to = {
  root: () => Routes.root,
  admin: () => Routes.admin,
  dashboard: () => Routes.dashboard,
  catalog: () => Routes.catalog,
  myOrders: () => Routes.myOrders,
  transactions: () => Routes.transactions,
  documents: () => Routes.documents,
  invoices: () => Routes.invoices,
  offers: () => Routes.offers,
  projects: () => Routes.projects,
  knowledgeBase: () => Routes.knowledgeBase,
  tickets: () => Routes.tickets,
  profile: () => Routes.profile,
  auth: () => Routes.auth,
  signIn: () => Routes.signIn,
  loginResident: () => Routes.loginResident,
  register: () => Routes.register,
  resetPassword: () => Routes.resetPassword,
  notFound: () => Routes.notFound,
}
