export const MOCK_CLIENT_TICKETS = [
  {
    id: 1,
    code: 'TKT-001',
    subject: 'Payment charged twice for invoice #1042',
    status: 'Open',
    priority: 'high',
    department: { id: 1, name: 'Billing' },
    created_at: '2026-05-10 10:00:00',
    updated_at: '2026-05-12 14:30:00',
    replies_count: 3,
    replies: [
      {
        id: 101,
        message: 'Hello, I was charged twice for invoice #1042 dated May 9th. The amount of $149.00 was debited from my card two times within 10 minutes. Please refund the duplicate charge as soon as possible.',
        author: { name: 'Alex Johnson', img: null },
        author_type: 'client',
        created_at: '2026-05-10 10:00:00',
      },
      {
        id: 102,
        message: 'Hi Alex, thank you for reporting this. We have confirmed the duplicate transaction on our end. Our billing team has initiated a refund for the extra charge of $149.00. It should appear on your statement within 3-5 business days.',
        author: { name: 'Support Team', img: null },
        author_type: 'admin',
        created_at: '2026-05-11 09:15:00',
      },
      {
        id: 103,
        message: 'Thank you for the quick response! I will watch for the refund. Could you also send a confirmation email with the refund transaction ID?',
        author: { name: 'Alex Johnson', img: null },
        author_type: 'client',
        created_at: '2026-05-12 14:30:00',
      },
    ],
  },
  {
    id: 2,
    code: 'TKT-002',
    subject: 'Cannot login after password reset',
    status: 'Open',
    priority: 'high',
    department: { id: 2, name: 'Technical' },
    created_at: '2026-05-11 09:00:00',
    updated_at: '2026-05-13 11:45:00',
    replies_count: 2,
    replies: [
      {
        id: 201,
        message: 'I reset my password using the forgot-password link but now I cannot log in at all. The system says my credentials are invalid even with the new password I just set. I have tried on Chrome and Firefox with the same result.',
        author: { name: 'Maria Santos', img: null },
        author_type: 'client',
        created_at: '2026-05-11 09:00:00',
      },
      {
        id: 202,
        message: 'Hi Maria, we are sorry for the inconvenience. We found a caching issue affecting password resets in the last 24 hours. Please try clearing your browser cookies and cache, then attempt to log in again. If the issue persists, we can manually reset your account from our side.',
        author: { name: 'Support Team', img: null },
        author_type: 'admin',
        created_at: '2026-05-13 11:45:00',
      },
    ],
  },
  {
    id: 3,
    code: 'TKT-003',
    subject: 'Feature request: bulk export of reports to PDF',
    status: 'Open',
    priority: 'low',
    department: { id: 3, name: 'Sales' },
    created_at: '2026-05-12 15:20:00',
    updated_at: '2026-05-12 17:00:00',
    replies_count: 1,
    replies: [
      {
        id: 301,
        message: 'It would be very helpful to have a bulk export feature that allows selecting multiple reports and downloading them all as a single PDF or a ZIP archive of PDFs. Currently I have to export each report one by one which takes a lot of time when I need to prepare monthly summaries for clients.',
        author: { name: 'David Kim', img: null },
        author_type: 'client',
        created_at: '2026-05-12 15:20:00',
      },
      {
        id: 302,
        message: 'Hi David, thank you for the great suggestion! We have logged this as a feature request and passed it to our product team. Bulk PDF export is something other users have also requested, so it is on our roadmap. We will notify you when it becomes available.',
        author: { name: 'Support Team', img: null },
        author_type: 'admin',
        created_at: '2026-05-12 17:00:00',
      },
    ],
  },
  {
    id: 4,
    code: 'TKT-004',
    subject: 'Milestone dates not saving in project editor',
    status: 'Closed',
    priority: 'medium',
    department: { id: 2, name: 'Technical' },
    created_at: '2026-05-08 08:30:00',
    updated_at: '2026-05-10 16:00:00',
    replies_count: 3,
    replies: [
      {
        id: 401,
        message: 'When I edit a milestone date in the project editor and click Save, the date reverts to the original value after refreshing the page. This happens consistently for all my projects. I am using the latest version of Chrome on Windows 11.',
        author: { name: 'Nina Petrov', img: null },
        author_type: 'client',
        created_at: '2026-05-08 08:30:00',
      },
      {
        id: 402,
        message: 'Hi Nina, thank you for the detailed report. We were able to reproduce the issue. It was caused by a timezone offset bug in the date serialization logic. We have deployed a fix to production. Could you please verify on your end?',
        author: { name: 'Support Team', img: null },
        author_type: 'admin',
        created_at: '2026-05-09 14:20:00',
      },
      {
        id: 403,
        message: 'I confirmed the fix is working now. Milestone dates are saving correctly. Thank you for the fast turnaround!',
        author: { name: 'Nina Petrov', img: null },
        author_type: 'client',
        created_at: '2026-05-10 16:00:00',
      },
    ],
  },
]

export const MOCK_CLIENT_INPUT_DATA = {
  departments: [
    { id: 1, name: 'Billing' },
    { id: 2, name: 'Technical' },
    { id: 3, name: 'Sales' },
  ],
  priorities: [
    { id: 'low', name: 'Low' },
    { id: 'medium', name: 'Medium' },
    { id: 'high', name: 'High' },
  ],
}
