import DOMPurify from 'dompurify'

export const sanitizeMessage = (value: string): string => {
  return DOMPurify.sanitize(value, {
    ALLOWED_TAGS: [
      'google-sheets-html-origin',
      'colgroup',
      'col',
      'iframe',
      'p',
      'br',
      'b',
      'u',
      's',
      'i',
      'em',
      'strong',
      'a',
      'ul',
      'ol',
      'li',
      'blockquote',
      'span',
      'div',
      'img',
      'table',
      'thead',
      'tbody',
      'tr',
      'th',
      'td',
      'caption',
      'hr',
      'style',
    ],
    ALLOWED_ATTR: [
      'src',
      'href',
      'target',
      'width',
      'height',
      'frameborder',
      'allowfullscreen',
      'style',
      'type',
      'xmlns',
      'cellspacing',
      'cellpadding',
      'data-sheets-baot',
      'border',
      'dir',
      'id',
      'rowspan',
      'colspan',
      'data-sheets-root',
      'data-sheets-baot',
    ],
  })
}
